### ISSUE TITLE
[BUG] ICMPv6 packet info is incomplete in UI

### ISSUE THREAD

**Issue by pmk21** [pesos/rshark#7]
**Description**

Right now there is no packet capture information or packet description for ICMPv6 packets. Although ICMPv6 protocol is not extensively used, it is necessary we complete it.

**How To Reproduce**

Capturing ICMPv6 packets using `rshark`.

**Expected Behavior**

Give brief information and description about ICMPv6 packets. 

**Desktop**

 - OS: Linux
 - Rust version: 1.45.1

**Additional context**

Incomplete lines -
https://github.com/pesos/rshark/blob/f0a1991a0ecfe5529fbd39e4e5454ba990302fc6/src/display/ui.rs#L348
https://github.com/pesos/rshark/blob/f0a1991a0ecfe5529fbd39e4e5454ba990302fc6/src/display/ui.rs#L461

**Comment by alastairmoody-madeye** [comment]
Hi! May I work on this issue if it isn't already taken up by someone else?

**Comment by pmk21** [comment]
Sure
