### ISSUE TITLE
Use explicit `Arc::clone()` instead of `.clone()` method

### ISSUE THREAD

**Issue by tfidfwastaken** [pesos/rshark#8]
The following lines use a `.clone()` method to get increment the reference counter for an  `Arc` struct: https://github.com/pesos/rshark/blob/f0a1991a0ecfe5529fbd39e4e5454ba990302fc6/src/main.rs#L57-L61

According to *The Rust Programming Language*, it is considered a better practice to use an explicit call to `Arc::clone()` so as to distinguish it from deep-copying a struct.

So the changes would be like:
```rust
let network_net_info = Arc::clone(&net_info);
// and so on for all structs of type Arc declared in the file
```

This issue is marked as `first-timers-only` which means PR's will only be accepted from those who have never contributed code to any Open Source project before.

**Comment by vatsalyatandon** [comment]
I would like to work on this task.

**Comment by tfidfwastaken** [comment]
Go ahead!
